### ISSUE TITLE
Number of occurrences is wrong in facet "status"

### ISSUE THREAD

**Issue by rerodak** [rero/rero-ils#10]
For example, with the [following search](https://ils.test.rero.ch/search?page=1&size=20&q=katakana) I get one occurrence for the status "on shelf" while there are five items linked to the record

**Comment by iGormilhit** [comment]
At this stage the status facet is quite misleading, you're right. In fact it says 1, because it counts the number of documents, not the number of items.
Maybe the facets behavior should be defined and be written into a user story. There are other problems regarding to this topic, for instance when two facets are selected.
