### ISSUE TITLE
The help menu should point to the public help page if clicked from public interface

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#1127]
**How it works**

The help button points to the wiki home : `/help/` both from the public and pro interface.

**Improvement suggestion**
If I click on the help button from the public interface, I should land on the public help `/help/aide-publique/`
If I click on the help button from the pro interface, I should land on the wiki home `/help/`

**Note**
Eventually set the link to `/help/public/` so that the documentation slugs stay in English. This requires to change the file names of Flask wiki. To confirm with @iGormilhit

**Comment by iGormilhit** [comment]
@zannkukai I'm reopening this issue because

The link should be `/public` in

https://github.com/rero/rero-ils/commit/4e1a72cc46752c1b41850f9386724b7f9fc0ce36#diff-f943f06d1ca912de73f3c646f930d3eeR136

to point to `help/public`, and the locale should be managed by the interface itself.

Sorry for our lack of precision here.
