### ISSUE TITLE
Item CHECKIN_1_1_2 does not work

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1334]
**Describe the bug**

Checkin of an item on shelf without request in another library does not put the item in transit.
This corresponds to action `CHECKIN_1_1_2` in the doc file https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md#checkin-form

**To Reproduce**

1. Create an item
2. Switch library
3. Check in this item
4. See the strange flash message
5. See the item status

**Expected behavior**

Status should be "IN_TRANSIT_TO_HOUSE".
The flash message should be "The item is in transit."
A line with the details should be displayed in the checkin form.

**Context**

* server: ils.test.rero.ch
* version: v0.13.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/97201722-11ca7d80-17b3-11eb-9524-dd9973c0f6f5.png)

**Comment by iGormilhit** [comment]
@pronguen Does "CHECKIN_1_1_2" refer to the corresponding action in https://github.com/rero/rero-ils/blob/dev/doc/circulation/actions.md#checkin-form, section 1.i.b?

I'm asking, because I thought that theses actions where automatically tested (unit tests), and should have identified this issue.

Maybe @BadrAly knows something about it.
