### ISSUE TITLE
In the pro patron account, some paid fees still appear.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1373]
**Describe the bug**

In the pro interface, patron account, tab Fees, some paid fees still appear.

**To Reproduce**
1. [Diagnostic wanted, it was impossible to reproduce]

**Expected behavior**

The paid fees should appear only in the fee history.

**Context**
* server: ilspilot.test.rero.ch
* version: v0.12.0

Proposed by the pilot libraries

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/98135031-acb40d80-1ebf-11eb-9d07-425947942056.png)

**Comment by iGormilhit** [comment]
@zannkukai It reminds me something, such as a PR that you proposed. Does it ring a bell to you? :bell:

**Comment by zannkukai** [comment]
@iGormilhit it seems not be linked. Subscriptions creation and transactions management come from 2 distinct modules.

**Comment by zannkukai** [comment]
For dark reasons some payment are not corresponding to the total amount. 
So the total due is not equals to 0 and the system consider this transaction as Open (no problem on backend).
For this transaction the total due is still "4.996003610813204e-16" CHF (you can see it, clicking on "pay all" action button

![image](https://user-images.githubusercontent.com/10031585/98222347-ff89d580-1f50-11eb-9b69-54a1ef057a5e.png)

The problem is now : how to know how this strange amount is has been placed ?

![image](https://user-images.githubusercontent.com/10031585/98222508-35c75500-1f51-11eb-9ca1-cbe42e05f1eb.png)

Simple solution : click on "pay all" to create an new payment event and closed the transaction.

**Comment by pronguen** [comment]
@zannkukai
The problem was probably that a payment was done partially
* Example: fee CHF 0.20
* Payment: CHF 0.199
* Remaining fee: CHF 0.00 (rounded)

Solution: prevent to pay an amount with 3 digits after comma? Would it be possible?

**Comment by zannkukai** [comment]
Problem found ! It's due to bit reprsentation of real number in python 
```
$ python
Python 2.7.12 (default, Jul 21 2020, 15:19:50) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 10 - 9.54
0.46000000000000085
>>> 
```
