### ISSUE TITLE
Solve navigation inconsistencies in the professional interface

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#1645]
**How it works**

Some inconsistencies exist about the navigation in RERO ILS (professional view).

**Improvement suggestion**

* Document view, serial holdings: replace the file-text-o button (already in use for the quick receive on the holdings view) by an eye button (which is going to mean "display").

Already solved

* Item view: add an Edit and Delete button (for all type of items).
* Holdings view: remove the eye button to access an issue. The access is done via a link on the field `enumerationAndChronology`, so that it is placed on the left as in the document view.
    * solved by https://github.com/rero/rero-ils-ui/pull/796 in February 2022

**Comment by pronguen** [comment]
I think that a certain harmonisation is needed globally. List of points:
- holdings/item detailed view: link to the host document should be displayed in the same way
- links to items and holdings from document/hodlings detailed view. Currently, there are accessible through buttons (with 2 different icons: eye, document) and through links on the barcode. The buttons have the problem that they cannot open the link in a new tab.

**Comment by zannkukai** [comment]
@pronguen The buttons linked to the holdings are only present for serial holding. If we allow to edit a normal holding, there are no logic in the backend to cascade holding changes to related items (location, circulation category, document). 
Additionally there are currently no "delete" button because it will always disable with cause than item are linked to it. The logic in te backend is : when last item related to an holding is deleted, then delete the holding.

The "document" icon isn't to link to the document view, but for "Bulettinage" of serial holding. (maybe a better icon ? suggestion ?)

@pronguen no problem to remove the eye button --> link on enumerationAndChronology. 

If you would change these behaviors, it will affect a lot of backend code/logic.
@BadrAly What's your feeling about these problems ?

**Comment by pronguen** [comment]
@zannkukai 

> @pronguen The buttons linked to the holdings are only present for serial holding. 

Yes, that's ok. Don't add anything to the non serial holdings. This is not specified in this issue.

> The "document" icon isn't to link to the document view, but for "Bulettinage" of serial holding. (maybe a better icon ? suggestion ?)

No. If you click on it, it does not execute a *bulletinage*, it just opens the holdings detailed view. From that view, we can do the actual *bulletinage*. This is the inconsistency. For this reason, we wrote (main text of this issue):
*Document view, serial holdings: replace the file-text-o button (already in use for the quick receive on the holdings view) by an eye button (which is going to mean "display")*
