### ISSUE TITLE
"To pick up until" in the notifications does not work

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2140]
**Describe the bug**

In the `availability` notification, the date after "To pick up until" is empty.

The template indicate `{{ library.next_open }}` without mentioning the min. 10 days. Is it right?

**To Reproduce**

1. Generate a notification `availability` in the circulation interface
2. See the notification

**Expected behavior**

The date should be: at least 10 days after the notification, ideally delayed until the next open day.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.4.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/125098124-0e73e980-e0d7-11eb-931b-44577c08957b.png)

**Comment by zannkukai** [comment]
@pronguen
It seems good to us `library.next_open`. You can't say always 10 days after because the library could be closed at this date.
The behavior is to compute the next_open of `current_date + 9` :: the minimum date will be 10 days after current_date, but if library is closed at this date, the computed date could be +11, +12, ... depending of library setting and exception dates.

**Comment by pronguen** [comment]
@zannkukai I adapted the main text of the issue. What you describe is correct. Main problem is that the pick-up date is not displayed at all.
