### ISSUE TITLE
Item location not populated in item editor 

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#217]
Even though the location of the item is correctly displayed in the document with items window, in the  Item editor the location is empty:

<img width="1253" alt="Screen Shot 2019-03-13 at 14 25 48" src="https://user-images.githubusercontent.com/26998238/54282261-ea9e4880-459b-11e9-8ad8-f887d464bc79.png">

<img width="1360" alt="Screen Shot 2019-03-13 at 14 25 18" src="https://user-images.githubusercontent.com/26998238/54282240-dc502c80-459b-11e9-8be8-09e363b4626c.png">

**Comment by iGormilhit** [comment]
@BadrAly 

That's an interesting case, that should be taken care of by Consortium WG. The situation is the following: when, as a librarian working in the library 4 (for instance), if I edit an item owned by another library, then I wouldn't have any localisation in the select field, because I cannot attribute a location that's not in my library to an item...

**Comment by iGormilhit** [comment]
@BadrAly This is fixed, isn't it?

**Comment by BadrAly** [comment]
> @BadrAly This is fixed, isn't it?

@iGormilhit Yes, cause the libraian will not have access to items of other ogranisation.
