### ISSUE TITLE
Fix item sorting for standard holdings

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2243]
**How it works**

When a holdings (type standard) has a lot of items, the items are not sorted, thus finding a specific item is not an easy task.

**Improvement suggestion**

The items are sorted by the field unit (`enumerationAndChronology`) descending (higher unit to smaller unit). This sort should be alphabetical but should sort numbers **by their numeric value and not as strings**. 

Explore the collation keyword ES type: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation-keyword-field.html

This concerns only standard holdings. Serial holdings are already sorted according to another logic.

**Screenshot**

Example of an holdings (within [this document](https://bib.rero.ch/rbnj/documents/10936)) where the items could be sorted by the unit field value: left pro, right public view

![image](https://user-images.githubusercontent.com/8154915/137672891-56413a3c-748a-4b99-a66f-7520fb039a74.png)

**Comment by PascalRepond** [comment]
Lexicographic sorting as used in the public view does not work here, since "6" is considered higher than "59" (example here : https://bib.rero.ch/rbnj/documents/1020808). Roman numbers will pose similar problems for sorting.

![image.png](https://images.zenhubusercontent.com/60bf791a5b600c169e5778a4/d5e34920-7593-477c-8041-132003da3956)

We have to find a better way to sort the items in both public and professional views.
