### ISSUE TITLE
Redirect to document detailed view after document or item edition.

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#226]
When I create/edit and save a record, I land on a results page.
I should land on the detailed view of the recently edited/created record.

**Comment by iGormilhit** [comment]
It depends on the type of record.

Most of the time, there's no detailed view (libraries, circulation policies, item types, patron types, patron). In that cases, maybe, the result page is a good solution. But, the edited record should be on top of the list.

And the filters should be kept (ie, I used the facets to find a record, edit it, and then I get the result list again). Or not, but we should decide it.

In the end, it's when we edit a document or an item, we should be redirected to the document detailed view. In any case, because we can edit document and item from the admin view or from the document detailed view.

**Comment by pronguen** [comment]
@iGormilhit 

Exact, thank you for the precision.
* For records having a detailed view (at least documents, in the future also patrons): we should display this detailed view.
* For the other records, we should display - if possible - the page where the user was when he clicked on "Edit", that is a result page including all the navigation elements (facets, page number (if the user is on the 3rd results page for ex.), etc.).

**Comment by iGormilhit** [comment]
So, let's prioritize things.

First thing first, make the edition of documents and items consistent. And then we will think of other cases.

**After editing a document or an item, either from the professional search view or from the public document detailed view, the librarian should be redirected to the document detailed view.**
