### ISSUE TITLE
Search engine optimisation (organisation name, test instances)

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2280]
**How it works**

* searching for "catalogue rero" in Google brings the old Explore URL
* searching for "rero ils" in Bing brings first the ils.test.rero.ch results

**Improvement suggestion**

* the organisation name is indexed in the title of the view homepage, so that it should be possible de find `bib.rero.ch/vs` by searching for "rero valais"
* keyword "catalogue/catalog/katalog/catalogo" is indexed in the global and view homepages
* sitemap is created on the global URL with links to the organisation homepages
* ideally some specific keywords can be defined for depending on the instance, for indexation in the header of the homepage
* global homepage is announced to the main search engines (Google, Bing, DuckDuckGo, Ecosia, Yahoo, Qwant)
    * bib.rero.ch was announced to Google
* adding a robot.txt to prevent the indexing the test and dev instances ?

**Comment by iGormilhit** [comment]
That's also why we need to configure the `<title>` of the RERO ILS pages. Now it's everywhere "RERO ILS".

![ksnip_20210825-150957](https://user-images.githubusercontent.com/1557213/130797205-1ca05456-f57d-4da3-a4f6-97dc12575ebb.png)
I think that for Google bib.rero.ch is the new explore. It may be due to the redirection HTML code.

![ksnip_20210825-151620](https://user-images.githubusercontent.com/1557213/130797408-f6fd0433-657c-4ac8-be4f-a01be1b6d7e8.png)
