### ISSUE TITLE
Request list: all items with a temporary circulation category are hidden

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2296]
**Describe the bug**

Request list: all items with a temporary circulation category are hidden.

**To Reproduce**

1. Create an item that can be requested, or take an existing one
2. Add him a temporary circulation category with `negative_availability:true`
    * See that it is not in the request list (`/professional/circulation/requests`) > correct
3. Change the item to have a temporary circulation category with `negative_availability:false`
    * See that it is not in the request list (`/professional/circulation/requests`) > **it should be because it is available**

**Expected behavior**

Request list:
* items with a temporary circulation category with `negative_availability:true` **should not** be part of this list
* items with a temporary circulation category with `negative_availability:false` **should** be part of this list

The list should display the same request that are addressed by the notification `request`. The conditions should be coded together/factored.

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.4.6`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
@pronguen
Not sure to well understand the workflow. If an item appears into the `circulation/request` page, it's because a request has been created on it before (in a time where this item was available). If we change the availability of the item, is that the corresponding request should be hide ? 

Using this behavior, we couldn't change the status/cancel (at this time it's not yet  possible). 
I would be sure to not work now and change the behavior in some weeks.

In all cases, if an item has a temporary location with `negative_availability=false` : I'm agree, it should always appears in the list.
