### ISSUE TITLE
Reminders notifications are not generated correctly

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2303]
**Describe the bug**

Reminders notifications are not generated correctly. For a due date on 2021-08-14, only one reminder should have been generated, but they are all (1st, 2nd, 3rd and 4th) generated, merged and sent in the same notification, even if the communication channel is different (4th should be per mail).

See example. 

**To Reproduce**

See example

**Expected behavior**

Notifications are grouped only if they have
* same recipient (either library or patron) AND same communication channel

Reminder notifications are generated on the right date.

**Context**

* server: <https://bib.rero.ch>
* version: `v1.4.6`

**Example**

Due date of all items is 14.08.
One of the loans: https://bib.rero.ch/api/loans/160064 - vs

```txt
Titre : Aquitaine : Bordelais, Landes, Pays basque, Béarn, Lot-et-Garonne / Echéance : 13.08.2021 Note : deuxième rappel
Titre : Aquitaine : Bordelais, Landes, Pays basque, Béarn, Lot-et-Garonne / Echéance : 13.08.2021 Note : premier rappel
Titre : Aquitaine : Bordelais, Landes, Pays basque, Béarn, Lot-et-Garonne / Echéance : 13.08.2021 Note : quatrième rappel
Titre : Aquitaine : Bordelais, Landes, Pays basque, Béarn, Lot-et-Garonne / Echéance : 13.08.2021 Note : troisième rappel
Titre : Lyon et sa région / rédaction Luc Decoudin ... [et al.] Echéance : 13.08.2021 Note : deuxième rappel
Titre : Lyon et sa région / rédaction Luc Decoudin ... [et al.] Echéance : 13.08.2021 Note : premier rappel
Titre : Lyon et sa région / rédaction Luc Decoudin ... [et al.] Echéance : 13.08.2021 Note : quatrième rappel
Titre : Lyon et sa région / rédaction Luc Decoudin ... [et al.] Echéance : 13.08.2021 Note : troisième rappel
Titre : Pyrénées, Toulouse, Gers / Echéance : 13.08.2021 Note : deuxième rappel
Titre : Pyrénées, Toulouse, Gers / Echéance : 13.08.2021 Note : premier rappel
Titre : Pyrénées, Toulouse, Gers / Echéance : 13.08.2021 Note : quatrième rappel
Titre : Pyrénées, Toulouse, Gers / Echéance : 13.08.2021 Note : troisième rappel
Titre : Périgord Quercy : Dordogne Lot / Echéance : 13.08.2021 Note : deuxième rappel
Titre : Périgord Quercy : Dordogne Lot / Echéance : 13.08.2021 Note : premier rappel
Titre : Périgord Quercy : Dordogne Lot / Echéance : 13.08.2021 Note : quatrième rappel
Titre : Périgord Quercy : Dordogne Lot / Echéance : 13.08.2021 Note : troisième rappel
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8154915/129864771-bea4cb6a-1031-4972-9847-7f371fd54b8e.png)

**Comment by zannkukai** [comment]
**about "Reminder notifications are generated on the right date" problem **

It's really complicated to trace the reminders generation process without all informations and configurations + access to server log (`current_app.logger`).

In this case the "problem" (if it exists - we need to check cipo configuration), is that the system consider that this overdue loan must generate 4 overdue reminders https://github.com/rero/rero-ils/blob/fa4fde322d10263982b8618adaf1b625723aa90a/rero_ils/modules/notifications/tasks.py#L87-L96

--> The last line, return 4 overdue reminders to generate for the corresponding open days since due_date ; none are already sent, then fourth are generated in the same time.

The reasons could be : 
  - bad/strange cipo configuration.
  - the notifications tasks doesn't works for few days, then run and generate all notifications at once.
  - updated loan information (due_date / library) by CLI

Note : `library.count_open()` and `cipo.get_reminders()` functions seem correctly tested by unittest code.

**about "group notification by communication channel" problem.**

I created into the https://github.com/rero/rero-ils/pull/2312 PR a new aggregations subdivision to group notification by communication channel.
