### ISSUE TITLE
Checkout possible only after cancelling the request of the patron

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#2367]
**Describe the bug**

Patron A checked out an item (pid: 1858489, org 1). Patron B requested this item. Patron A checked the item in. Patron B came to the desk to borrow it, but the circulation interface refused to check it out, because it was already on loan. The librarian cancelled the request of patron B and the checkout was possible.

**To Reproduce**

Still to be reproduced.

**Expected behavior**

After the checkin by the patron A, the item should be in a state  that allow the checkout for the patron B.

**Context**

* server: <https://bib.rero.ch>
* version: `v1.4.8`.

**Comment by BadrAly** [comment]
This behaviour can be reproduced in three cases (checkout of ITEM_AT_DESK loan):

1. when there are two `ITEM_ON_LOAN` loans for the same transactions. The `validate` action cancels the first loan and then changes the state of the `PENDING` loan to `ITEM_AT_DESK`. When the systems tries to checkout the `ITEM_AT_DESK` loan, it finds another `ITEM_ON_LOAN` loan and it fails. This case is fixed in `1.5.0` (fix to prevent having duplicate loans at checkout).

2. when the owning library of the item has no location with `is_pickup= True`.  -> additional analysis in progress

3. when item status remains `on_loan` after a successful checkin (problem related to indexing of item after loan change). -> additional analysis in progress
