### ISSUE TITLE
Cancellation of a request leads in some cases to the wrong item status

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2454]
**Describe the bug**

Cancellation of a request leads in some cases to the wrong item status. This concerns the action `CANCEL_REQUEST_4_1_2` (see [spec here](https://github.com/rero/rero-ils/blob/master/doc/circulation/actions.md)).

> 1. __CANCEL_REQUEST_4__: item in_transit (IN_TRANSIT_FOR_PICKUP)
> 	1. __CANCEL_REQUEST_4_1__: loan to cancel = current loan
> 		1. __CANCEL_REQUEST_4_1_1__: PENDING loan does not exist → (update loan, item is: in_transit (IN_TRANSIT_TO_HOUSE))
> 		1. __CANCEL_REQUEST_4_1_2__: PENDING loan exists → (cancel loan, item is: in_transit (IN_TRANSIT_FOR_PICKUP))[automatic validate logic is applied next PENDING loan] 
> 	1. __CANCEL_REQUEST_4_2__: loan to cancel != current loan → (cancel loan, item is: in_transit (IN_TRANSIT_FOR_PICKUP))

When cancelling a loan that is in transit for pickup, and the next pending loan has a pick-up location equals to the item location, the loan becomes "ITEM_AT_DESK". This is wrong, because the item is de facto still in transit.

**To Reproduce**

1. Login at library L1
1. Add a request for patron P1 on item I1 of your own library, with pick-up location L2/1 (not in library L1)
1. Add a request for patron P2 on same item, with pick-up location L1/1 (within your login library L1)
1. Validate the request for P1 > the item goes "in transit for pick-up"
1. Cancel the request for P1 > the item goes "at desk", this is not correct

**Expected behavior**

In case of a `CANCEL_REQUEST_4_1_2`, the item stays "in transit" and the next loan becomes "IN_TRANSIT_FOR_PICKUP".

**Context**

* server: [ils.test.rero.ch][1]
* version: `v1.5.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by zannkukai** [comment]
@BadrAly Is it normal to have 2 triggers possible transitions for PENDING triggering "validate_request" (https://github.com/rero/rero-ils/blob/staging/rero_ils/config.py#L2668-L2678).

I don't understand how `invenio-criculation` can determine which one to use. I think it validates the first transition ; try to execute the second but at this time, the item/loan doesn't satisfy the conditions so it fails.

**Comment by zannkukai** [comment]
## dev notes
The initial problem seems occurs here

https://github.com/rero/rero-ils/blob/b98d030da13fc3055d755cb18d5b544fc8dd0088/rero_ils/modules/items/api/circulation.py#L483-L488

Before the loan cancelling, the item status was "in_transit". After this call the item status is "on_shelf".
**TODO** :: is it correct ?

After the loan canceling, the next step is to validate the first pending request. According to circulation transition configuration, two transitions is possible in this case.

https://github.com/rero/rero-ils/blob/b98d030da13fc3055d755cb18d5b544fc8dd0088/rero_ils/config.py#L2927-L2936

Transitions are checked in order where it placed. So as first one is valid, the first pending request state updates to `ITEM_AT_DESK` because pickup_library_pid equals transaction_library_pid

https://github.com/rero/rero-ils/blob/b98d030da13fc3055d755cb18d5b544fc8dd0088/rero_ils/modules/loans/utils.py#L217-L220

At this time : 
  * the cancelled loan is correct.
  * the item status should be "IN_TRANSIT" instead of "AT_DESK"
  * first pending request(loan) state is "ITEM_AT_DESK" instead of "IN_TRANSIT_FOR_PICKUP"

**Comment by zannkukai** [comment]
### dev notes.

the item status changed during the `cancel_loan` call. It's due to `change_status_commit_and_reindex()` method called into the `@add_action_parameters_and_flush_indexes` decorator call.
