### ISSUE TITLE
Online items should be displayed the same way in public and pro interface

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2493]
**How it works**

The 'status' facet shows 'no result' for the online resource.
In the search result (professional and public view), we can see the status 'available'.
![image](https://user-images.githubusercontent.com/12396034/139833578-275c8d9f-29d2-47bd-a85a-93976b63bb6a.png)

In the document detail view, we can see that it displays the online type location differently.
public view
![image](https://user-images.githubusercontent.com/12396034/139832602-f0855142-8466-44d6-b88c-43374941c547.png)

professional view
![image](https://user-images.githubusercontent.com/12396034/139832557-73bda34d-8482-4562-92d6-428fb9b18344.png)

**Improvement suggestion**

1/ Add an 'online' facet. (this is part of an US on Taiga)
2/ The display of the online location should be the same whether in the public or the professional view. [low] Or display the circulation information of the online item type. It is not displayed in the public interface [bug].

**Comment by pronguen** [comment]
An idea was to create items for harvested online resources, so that they have a real "status" and can appear in the facet. According to @Garfield-fr this would be overkill as the items would be useless (no requests, no loans on them). Only holdings are needed.

Other point: it could be an effort to correct the "Status" facet because all holdings data are present in the document, not only the data of a specific organisation.
