### ISSUE TITLE
Impossible to delete a patron when he/she has returned items still in transit

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2532]
**Describe the bug**

Impossible to delete a patron when he/she has returned items still in transit

**To Reproduce**

1. Create a patron
2. Check-out an item
3. Check-in this item so that it goes in transit
4. Try to delete the patron

**Expected behavior**

It should be possible.

**Context**

* server: bib.rero.ch
* version: `v1.6.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by BadrAly** [comment]
Any new action on `active` loan requires access to the `patron` of this loan.
 In this case:
1. The `in_transit` loan remains `active` until the item is returned at the `owning_library`. 
2. when receiving the item at the owning library, the system needs the `patron` information to populate the `operation_log` and to place the `receive` action itself. 

I do not see the problem waiting until the `item` arrives home and then remove the `patron`. otherwise, we need to invest a lot of efforts to recreate the `receive` action

**Comment by PascalRepond** [comment]
I propose to close this issue as `wontfix` as the effort will remain disproportionate compared to its value.
