### ISSUE TITLE
Error when deleting a fine 

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2602]
**Describe the bug**

The following error message:

"payment creation failed!
[400 - undefined] Server error 8.2 is not a multiple of 0.01
"
appears when deleting the amount of "8.2" for a patron having fees equal or greater than "8.2" CHF

The transaction is successful if the amount of the fee is in the format "8.20" [two decimals]

**To Reproduce**

1. Go to the admin interface
2. Locate a patron having open fees
3. Try to delete a fee for this patron
4. Enter an amount with one decimal
5. you see the error above

* server: [bib.test.rero.ch][1] or [bib.rero.ch][2]
* version: `v1.7.0`

<img width="895" alt="Screenshot 2021-12-16 at 15 46 25" src="https://user-images.githubusercontent.com/26998238/146394392-da5cc197-d941-48a0-a06a-97236752fdf0.png">

**Comment by BadrAly** [comment]
Problem duplicated in console as well when creating an `PatronTransactionEvent` record
```

ValidationError: 8.2 is not a multiple of 0.01

Failed validating 'multipleOf' in schema['properties']['amount']:
    {'minimum': 0, 'multipleOf': 0.01, 'title': 'Amount', 'type': 'number'}

On instance['amount']:
    8.2
```

**Comment by zannkukai** [comment]
According to multiple sources in the web, it's seems that a very bad idea to store decimal.
* https://stackoverflow.com/questions/42495493/json-schema-giving-me-validation-errors-for-multipleof-0-01-for-any-number-endin
* https://github.com/Julian/jsonschema/issues/185
* http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.3
* https://stackoverflow.com/a/3730040

The easiest solution seems to store amount as cents counters instead of float => store 1025 instead of 10.25
Need a refactoring for the patron transactions but also for acquisition modules (second step ?)
