### ISSUE TITLE
Field `item.library` is not updated after a `location` update.

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#2676]
**Describe the bug**
In the backend (console) when a developer updates the `location` of an `item`.
If this `location` belongs to another library, then the field `item.library` is not updated.

**To Reproduce**
```
item['location'] = pid_of_location_of_another_library
item.update(item, dbcommit, reindex)
print(item.library)
show always the old library
```

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.8.0` 
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://bib.test.rero.ch
[2]: https://bib.rero.ch

**Comment by BadrAly** [comment]
Ideally, we need to remove the field `item.library` and calculate it in the `items_ES` if does not create problems for the `UI`

**Comment by zannkukai** [comment]
@BadrAly 
Is the real question isn't "why this `library` field is present into item" ? I supposed that if it's present, it's because it is used somewhere into the backend code... it seems used by circulation to determine which cipo used.
Maybe the best should be to implement a "pre_commit" Invenio extention to check if location field changed ; if yes update the library field if needed.
What's your feeling about this solution ?

**Comment by BadrAly** [comment]
@zannkukai it is a quick solution that can fix the problem. 
But eventually we need to update the `circulation` module to use the `location` to determine the `library` of the `item`. 
Are you the sure that nothing will change in the `UI` if we remove the `item.library`? I think this is important.

**Comment by zannkukai** [comment]
It seems I could be used here (need double check) :
https://github.com/rero/rero-ils-ui/blob/0fa0669b95c32eae767eddfc738fcb765cb32063/projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html#L79
https://github.com/rero/rero-ils-ui/blob/0fa0669b95c32eae767eddfc738fcb765cb32063/projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts#L101
https://github.com/rero/rero-ils-ui/blob/0fa0669b95c32eae767eddfc738fcb765cb32063/projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts#L135

**Comment by zannkukai** [comment]
@BadrAly 
I we use `item.location.pid` to search about item library, it could reduce circulation perf because we will introduce some "Library.get_record_by_pid()" calls to determine the library of an item.
Maybe nicer to remove the field, maybe safer to keep it and manage "location changed" behavior.
Should be discussed with other PO/devs
