### ISSUE TITLE
Item tasks: temporary locations are not cleaned correctly

### ISSUE THREAD

**Issue by PascalRepond** [rero/rero-ils#2694]
**Describe the bug**

The daily task `rero_ils.modules.items.tasks.clean_obsolete_temporary_item_types` doesn't seem to work as intended. It runs without errors but temporary location in items remains after its due date.

**To Reproduce**

1. Set a temporary location for an item with a deletion date
2. After the deletion date is passed, the item still has its temporary location

**Expected behavior**

Temporary locations with overdue deletion dates should be deleted daily by the system. 

**Context**

* server: [ils.test.rero.ch][1] or [bib.rero.ch][2]
* version: `v1.8.0` or the commit hash (see frontpage).

[1]: https://ils.test.rero.ch
[2]: https://bib.rero.ch

**Comment by BadrAly** [comment]
@PascalRepond Currently, we have only one implemented task to delete the expired `temporary_item_types`-> `clean_obsolete_temporary_item_types`. Do you want to extent this functionality to delete the expired `temoprary_locations`? I assume that the removal of the expired `temporary_item_types` works fine and the problem is only with the `temoprary_locations`. Please confirm.

**Comment by PascalRepond** [comment]
@BadrAly OK, yes thir functionnality should be extended to `temporary_locations` as well. I cannot confirm yet if it works fin with `temporary_item_types` but I am testing it. 
In any case, if a deletion task for `temporary_location` is not implemented, it should be. Thank you.
