### ISSUE TITLE
Error "400 Bad request" sometimes when opening or editing an item

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2705]
**Describe the bug**

See video. This error has been spotted only since v1.8.0.
* The URL of the item detailed view in the browser navigation bar is wrong in the video: but we see that the target URL in the item brief view is correct...

In the console, we have the following messages:
* Cookie “ILSPILSRVRID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [643470](https://bib.rero.ch/professional/records/documents/detail/643470)
* Error: getTranslators: detection is already running

Maybe linked to #2277 and the PR that corrected it.

**To Reproduce**

The error is not systematic. See video (cache was disabled).

**Expected behavior**

No error

**TO DO**

See comments below

**Context**

* server: bib.rero.ch
* version: `v1.8.0`

**Screenshots**

https://user-images.githubusercontent.com/8154915/154236756-6585b9ee-90fd-4d2e-8666-bb4b28b78179.mp4

**Comment by PascalRepond** [comment]
According to UCL, this seems to only happen after an inactivity period on the browser tab. Refreshing the page before clicking if the page has been open for a while avoids this problem.

**Comment by jma** [comment]
The problem comes from here: https://github.com/rero/rero-ils-ui/blob/1ab892a4b6c196d3deadf94ba5f4d3377956ec1f/projects/admin/src/app/service/app-router-event.service.ts#L63

after 30' of inactivity the user is removed from the local storage.

Proposition:

- do not store the current user in the local storage but in the user service only. Remove all related code. Change the 400 status in 401 here: https://github.com/rero/rero-ils-ui/blob/8f9e2cc237265072982c4dc82438fb5c3669c02a/projects/admin/src/app/guard/can-access.guard.ts#L52
