### ISSUE TITLE
Syntax error in stale.yml GitHub Workflow

### ISSUE THREAD

**Issue by bertvandepoel** [rero/rero-ils#3217]
I was talking to a friend about how I have to check up on an issue here from time to time or it gets closed by the GitHub Actions bot. He thought this was weird, so he looked at https://github.com/rero/rero-ils/blob/staging/.github/workflows/stale.yml and remarked that there's a mistake in this file. The comment on https://github.com/rero/rero-ils/blob/staging/.github/workflows/stale.yml#L16 seems to imply the intention is to not close but just to mark stale issues. However, 0 is not the correct value for "days-before-close:". The correct value is false. Therefore, after 180 days, the bot marks the issue as stale and immediately also closes it. This is not intended behaviour, so stale.yml should be edited to fix the syntax error, either with true if the current behaviour is desired or, in my opinion ideally, false to reflect the intention of the comment and to prevent relevant bugs waiting for someone to fix them from being closed.

**Comment by PascalRepond** [comment]
Hi and thanks for your issue. 

You are correct in that the comment in the file does not correspond to the actual behaviour. Rest assured that the project team is notified when an issue is closed and always reopened it if the issue was still relevant. We will nonetheless fix this behaviour to prevent automatic closing.
