### ISSUE TITLE
Suppress the 'acquisition_order' field in the library notification setting

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#3241]
### How it works

The `acquisition_order` notification type in library notification settings is not used.
The order is sent according to the email contact in the acquisition setting.

### Improvement suggestion

The field `acquisition_order` in the library notification settings is suppressed.

**Comment by zannkukai** [comment]
The `acquisition_order` is a valid and used notification type : it can't be deleted.
But the UI editor doesn't need to create a field for `acquisition_order` email because the email used when sending an order notification is either :
  - related vendor email
  - related library acquisition_setting email
  - custom email chosed by manager
 
 
![image](https://user-images.githubusercontent.com/10031585/216931875-4c80fcfa-2ae6-4163-9589-3f87fd7c7617.png)
