### ISSUE TITLE
User roles display

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#53]
* In the user record, the attribute "roles" should have all its possible values in the singular (especially patrons).
* In the user result list, the brief display of the roles should be enhanced, with a comma separating each role (if there are more than one).

**Comment by iGormilhit** [comment]
> In the user result list, the brief display of the roles should be enhanced, with a comma separating each role (if there are more than one).

This is fixed by https://github.com/rero/reroils-data/commit/730f0a447aa955a828a7b3a9059c875a02089384

![capture_117](https://user-images.githubusercontent.com/1557213/42199869-19aa5dd0-7e91-11e8-964f-e3a283410ed9.png)

> In the user record, the attribute "roles" should have all its possible values in the singular (especially patrons).

At the creation of roles, it makes sense that these are plural. A role is a group of people. There's the `admins` role, the `superusers` role. But we should be able to display them in singular form.
