### ISSUE TITLE
Location URI are not filtered by library for a system librarian

### ISSUE THREAD

**Issue by AoNoOokami** [rero/rero-ils#697]
**Describe the issue**
When creating or editing an item as a system librarian, the location URI are not filtered by library. For example, "Espaces publics" appears several times in the dropdown list (logged as Astrid)

**To Reproduce**
1. Log in as `reroilstest@gmail.com`
2. Create an item
3. Look at the dropdown list content

**Expected behavior**

**Software version**
https://ilsdev.test.rero.ch/
https://github.com/rero/rero-ils/commit/31e2ce436fb8cd48f275018fcb07f3baa65a8779

**Screenshots**
<img width="426" alt="Screen Shot 2020-01-14 at 12 27 11" src="https://user-images.githubusercontent.com/28982829/72340862-3b556500-36c9-11ea-870c-61bda8f60a80.png">

**Additional context**
N/A

**Comment by iGormilhit** [comment]
@AoNoOokami This is what is (was) awaited as Astrid is a system librarian. I can't find it yet, but I'm sure we thought of something like displaying library's code before the location name.

Now, we have the library switch, maybe this enumeration should be filtered accordingly.

Try with Virgile in order to see the difference.

**Comment by AoNoOokami** [comment]
Solved by https://github.com/rero/rero-ils-ui/pull/137
